### ISSUE TITLE
Composer issues

### ISSUE THREAD

**Issue by MarlonEtiene** [oscarotero/social-links#10]
Hello,

I have tried to install this package via composer same as
`composer required oscarotero/social-links`
and in my composer.json I have tried
```
"oscarotero/social-links": "dev-master"
```
In both cases I got this error
```
  Problem 1
    - The requested package oscarotero/social-links could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
In my composer.json I have `"minimum-stability": "dev",`

Can someone help me please?

Thank you in advance!

**Comment by oscarotero** [comment]
Hi.
The package name is `social-links/social-links` instead `oscarotero/social-links`.
You can see the composer.json file to check this.

**Comment by MarlonEtiene** [comment]
Ah ok!
I'll go try!

Thank you!
