### ISSUE TITLE
Google Classroom

### ISSUE THREAD

**Issue by joehobson** [oscarotero/social-links#11]
We'd really love to see a Google Classroom as a provider. Use of their platform is growing rapidly. We're using your library on the [Smithsonian Learning Lab](https://learninglab.si.edu) and our users would love this added feature. Thanks
https://developers.google.com/classroom/guides/sharebutton

**Comment by oscarotero** [comment]
Hello.
The guide shows how to create a share button using the javascript api, but it's not valid for this library that generates simply urls, without javascript.
I'm ok with adding Google Classroom provider but we need the url and the available parameters to create it.

**Comment by oscarotero** [comment]
Hello. I added the classroom provider but I cannot check it, maybe it's not available from Spain.
Can you test it in the demo page (https://oscarotero.com/social-links/demo/) and tell me if it works fine?

**Comment by joehobson** [comment]
Not sure on international access, but they have a developer program for setting up test Classroom environments: https://developers.google.com/classroom/access

I submitted the form for a test account but haven't heard back yet. I also got contact information from a colleague for someone at Google that may be able to help if your initial work wasn't successful.

I'll test on your demo page once my dev access to Classroom is approved. Thanks for jumping on this

**Comment by joehobson** [comment]
I got a dev account for Google Classroom and tried your demo page and it worked well. Screenshot attached. If logged in as a student, they have the option of attaching a web link to an assignment.

![screen shot 2016-04-01 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/838671/14214916/58403fd4-f805-11e5-9000-56b0d24553fe.png)

**Comment by oscarotero** [comment]
Good news!
I'll release the 1.9.0 version including this provided.
Thank you for the feedback.

**Comment by joehobson** [comment]
Thanks for getting the functionality added. It's up on our site now (though we need to make a new icon), under the sharing menu for collections and resources: https://learninglab.si.edu/collections/egyptian-hieroglyphs/XEd5rXyhUghHBx3L

**Comment by oscarotero** [comment]
Cheers
Happy to see it's working fine. :+1:
