### ISSUE TITLE
Share SMS link ?

### ISSUE THREAD

**Issue by ft23** [oscarotero/social-links#14]
https://jonathanstark.com/labs/sms-test.html

**Comment by oscarotero** [comment]
wow, that's great.
I've tested it with my smartphone (android) and only accept the body as query parameter `sms:14012341671;?body=TEST`
What are rests of options for? iOS?

**Comment by oscarotero** [comment]
Ok, I should search in stackoverflow before asking:
http://stackoverflow.com/questions/16165393/ios-sms-scheme-in-html-hyperlink-with-body

**Comment by ft23** [comment]
thanks for accept.
What do you think about them?

https://outlook.live.com/owa/?subject=ft23+like+your+plugin&body=https%3a%2f%2fgithub.com%2foscarotero%2fsocial-links&path=/mail/action/compose

https://mail.google.com/mail/u/0/?view=cm&fs=1&to&su=ft23+like+your+script&body=https://github.com/oscarotero/social-links&ui=2&tf=1

**Comment by oscarotero** [comment]
I don't use them because they are vendor specific email services and there's a generic "email" provider. But feel free to create a pull request if you like to include them in this package.
