### ISSUE TITLE
Some share counts return zero

### ISSUE THREAD

**Issue by rudzboy** [oscarotero/social-links#15]
Hi !
Using the test page : 

https://oscarotero.com/social-links/demo/index.php?url=http%3A%2F%2Fwww.nytimes.com%2F&title=&text=&image=&twitterUser=

Facebook and Twitter always return zero.
Twitter stopped sharing counts so might understand, but waht about FB ?

Do you have any idea how I might fix this ?

**Comment by oscarotero** [comment]
Thanks for your notice. I've fixed facebook counter to use the graph api instead the rest api and it's working now.
And about twitter, I've deactivated until find a new way of counting. Any contribution for this is welcome
Thanks

**Comment by oscarotero** [comment]
The new release fixes this.

**Comment by rudzboy** [comment]
Thank you for your quick answer, actually this bundle https://github.com/astina/AstinaSocialLinksBundle
uses at best the 1.8 version tag , do you know if the 1.11 version is compatible and if some PR should be made ?

**Comment by oscarotero** [comment]
This project uses [semantic versioning](http://semver.org/) so `1.x` versions should be compatible without breaking changes.
Anyway, the bundle requires `^1.8`, meaning 1.8 or upper 1.x version is compatible, including 1.11.

**Comment by rudzboy** [comment]
Yeah sorry about that one, I just noticed that, composer updating is just fine ;) Ty ;)
