### ISSUE TITLE
Facebook count not working

### ISSUE THREAD

**Issue by xianx** [oscarotero/social-links#21]
Hello,

I am trying to make a wordpress plugin with your plugin but the facebook count is not working. It always return zero. Please see the screenshot http://prntscr.com/hu7b48

My site is https and using nginx

Thanks.

**Comment by oscarotero** [comment]
Facebook count works fine to me (https://oscarotero.com/social-links/demo/?url=https%3A%2F%2Faulafilm.com%2F&title=&text=&image=&icon=&twitterUser=)
Are you sure your page have any share count?
