### ISSUE TITLE
VK share wrong parameters

### ISSUE THREAD

**Issue by g-rodigy** [oscarotero/social-links#22]
$page = new SocialLinks\Page([
		'url' =>  'http://mysite.com',
		'title' => 'title,
		'text' => 'text'
    ]);
    $page->vk->shareUrl 
    // return like http://vk.com/share.php?url=http://mysite.com&description=text&image=
   
The share url has wrong GET params:
 don't contain 'title' and parameter 'description'  not supported vk

**Comment by oscarotero** [comment]
v1.13.2 released with this fix.
