### ISSUE TITLE
Change whatsapp share URL

### ISSUE THREAD

**Issue by felcerreia** [oscarotero/social-links#26]
Is there any downside in using the URL "https://wa.me/?text=" instead of the "whatsapp://send?text=" ?

This usage is documented here https://faq.whatsapp.com/en/26000030/

**Comment by oscarotero** [comment]
Hi.
Yes, It seems a good alternative (and compatible with desktop browsers that may not have whatsapp app installed.
If it still working in mobile like now, I'm ok with this change. Do you want to work on a PR?
thanks!
