### ISSUE TITLE
Facebook ShareCount not working

### ISSUE THREAD

**Issue by bernhardh** [oscarotero/social-links#31]
I just tried out your demo with the following url `https://www.derstandard.at/`

As result I got 

![image](https://user-images.githubusercontent.com/642292/87048356-e91a7a00-c1fb-11ea-8a30-78468ec65282.png)

As you can see, I got 7 pinterest, but 0 Facebook, which is not true. The real values are 

![image](https://user-images.githubusercontent.com/642292/87048446-051e1b80-c1fc-11ea-9115-c6841d4adbca.png)

tested on https://www.sharedcount.com/

**Comment by oscarotero** [comment]
Yes, seems like Facebook api is deprecated and do not return anything. Example. https://graph.facebook.com/?id=https://www.derstandard.at/&fields=share

If you (or anyone else) knows how to fix this and return this data in 2020, please, let me know.
All these methods (https://stackoverflow.com/questions/5699270/how-to-get-share-counts-using-graph-api) does not work any more.

**Comment by bernhardh** [comment]
Found it out. You can still do it, but only with a valid access token.

```php
$access_token = $appId . '|' . $appSecret;
$url = "https://graph.facebook.com/?id=https%3A%2F%2Fderstandard.at&fields=engagement&access_token=" . $access_token;
```

You can get these credentials on https://developers.facebook.com/apps/ with your FB Account.

The main problem with this is, there is a request quota. 

![image](https://user-images.githubusercontent.com/642292/87283528-ac010100-c4f5-11ea-9d2b-4906d442168d.png)

And the quota is really low.
