### ISSUE TITLE
PHP version issue

### ISSUE THREAD

**Issue by rbrecht** [oscarotero/social-links#6]
For a new project with symfony 2.7 I wanted to use your social-links library, but there is an Issue in your code, so I cannot use it.

Symfony 2.7 requres "php": ">=5.3.3", and in your composer.json:
"require": {
	"php": ">=5.3.0"
},

But in you Page.php you are using the php 5.4 shorthand for array() like:
...
protected $providers = [];
...
$data = [];
...

Please update your code to valid php 5.3 or change your requirements in composer.json. PHP 5.3 is still supported by the most frameworks / server, so using shorthand code would not work on the most environments yet.

**Comment by oscarotero** [comment]
Yes, you're right.
I've released a new version that fix the php 5.3 support.
Thank you

**Comment by rbrecht** [comment]
Now it works like a charm!
Thanks alot :+1:
